apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-public-pvc
  namespace: nabu
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-nabu-obsidian-public-pv
  storageClassName: ""