apiVersion: apps/v1
kind: Deployment
metadata:
  name: nabu-lens
  namespace: nabu-beta
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 5m"
    keel.sh/match-tag: "true"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nabu-lens
  template:
    metadata:
      labels:
        app: nabu-lens
    spec:
      containers:
        - name: nabu-lens
          image: ghcr.io/lookitval/nabu-lens:beta
          imagePullPolicy: Always
          ports:
            - containerPort: 3000