apiVersion: v1
kind: Service
metadata:
  name: nabu-lens-service
  namespace: nabu-beta
  annotations:
    tailscale.com/expose: "true"
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: nabu-lens
  type: NodePort