apiVersion: v1
kind: Service
metadata:
  name: nabu-core-service
  namespace: nabu-beta
  annotations:
    tailscale.com/expose: "true"

spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nabu-core
  type: ClusterIP