apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-obsidian-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.86.170
    path: /shared/obsidian/vault01
  mountOptions:
    - nfsvers=4.1
    - hard