apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-pvc
  namespace: obsidian
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-obsidian-pv
  storageClassName: ""