apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nabu-postgres-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.86.170
    path: /shared/nabu/postgres
  mountOptions:
    - nfsvers=4.1
    - hard