apiVersion: v1
kind: Service
metadata:
  name: nabu-postgres-service
  namespace: nabu
  annotations:
    tailscale.com/expose: "true"
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: nabu-postgres
  type: ClusterIP
