apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nabu-postgres
  namespace: nabu
spec:
  replicas: 1
  serviceName: nabu-postgres-service
  selector:
    matchLabels:
      app: nabu-postgres
  template:
    metadata:
      labels:
        app: nabu-postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: nabu_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
