apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth-sync
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: tailscale-operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: TAILSCALE_ID
    - secretKey: client_secret
      remoteRef:
        key: TAILSCALE_SECRET