apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: laravel-secrets-sync
  namespace: link-preview-studio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: laravel-secrets
    creationPolicy: Owner
  data:
  - secretKey: app_key
    remoteRef:
      key: LINK_PREVIEW_STUDIO_APP_KEY