apiVersion: v1
kind: Service
metadata:
  name: link-preview-backend
  namespace: link-preview-studio
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: link-preview-backend
  type: ClusterIP