apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds-sync
  namespace: nabu-beta
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: postgres-creds
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: NABU_POSTGRES_USER
  - secretKey: password
    remoteRef:
      key: NABU_POSTGRES_PASSWORD