apiVersion: v1
kind: Service
metadata:
  name: nabu-postgres-service
  namespace: nabu-beta
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: nabu-postgres
  type: ClusterIP
