apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nabu-obsidian-private-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.86.170
    path: /shared/obsidian/private
  mountOptions:
    - nfsvers=4.1
    - hard